name: Integration Tests

on:
  push:
    branches:
      - '**'

jobs:
  openshift:
    name: Integration Tests using OpenShift Cluster
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        openshift: [v3.11.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.4
        with:
          oc version: ${{ matrix.openshift }}
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Install and Run Integration Tests
        run: mvn -B clean verify
